version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: hospitalchat-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: felipe0510
      MYSQL_DATABASE: hospitalchat
      MYSQL_USER: root
      MYSQL_PASSWORD: felipe0510
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
