-- DropForeignKey
ALTER TABLE "EXAM" DROP CONSTRAINT "EXAM_createdById_fkey";

-- DropForeignKey
ALTER TABLE "EXAM" DROP CONSTRAINT "EXAM_hospitalId_fkey";

-- DropForeignKey
ALTER TABLE "EXAM" DROP CONSTRAINT "EXAM_patientId_fkey";

-- DropForeignKey
ALTER TABLE "EXAM" DROP CONSTRAINT "EXAM_providerId_fkey";

-- DropForeignKey
ALTER TABLE "MESSAGE" DROP CONSTRAINT "MESSAGE_roomId_fkey";

-- DropForeignKey
ALTER TABLE "MESSAGE" DROP CONSTRAINT "MESSAGE_senderId_fkey";

-- DropForeignKey
ALTER TABLE "MESSAGE_VIEWED_USER" DROP CONSTRAINT "MESSAGE_VIEWED_USER_messageId_fkey";

-- DropForeignKey
ALTER TABLE "MESSAGE_VIEWED_USER" DROP CONSTRAINT "MESSAGE_VIEWED_USER_userId_fkey";

-- DropForeignKey
ALTER TABLE "PATIENT" DROP CONSTRAINT "PATIENT_hospitalId_fkey";

-- DropForeignKey
ALTER TABLE "ROOM" DROP CONSTRAINT "ROOM_adminId_fkey";

-- DropForeignKey
ALTER TABLE "ROOM" DROP CONSTRAINT "ROOM_hospitalId_fkey";

-- DropForeignKey
ALTER TABLE "ROOM_USER" DROP CONSTRAINT "ROOM_USER_roomId_fkey";

-- DropForeignKey
ALTER TABLE "ROOM_USER" DROP CONSTRAINT "ROOM_USER_userId_fkey";

-- DropForeignKey
ALTER TABLE "SCHEDULING" DROP CONSTRAINT "SCHEDULING_createdById_fkey";

-- DropForeignKey
ALTER TABLE "SCHEDULING" DROP CONSTRAINT "SCHEDULING_hospitalId_fkey";

-- DropForeignKey
ALTER TABLE "SCHEDULING" DROP CONSTRAINT "SCHEDULING_patientId_fkey";

-- DropForeignKey
ALTER TABLE "SCHEDULING" DROP CONSTRAINT "SCHEDULING_providerId_fkey";

-- AlterTable
ALTER TABLE "EXAM" ALTER COLUMN "createdById" DROP NOT NULL,
ALTER COLUMN "providerId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "MESSAGE" ALTER COLUMN "senderId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "ROOM" ALTER COLUMN "adminId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "SCHEDULING" ALTER COLUMN "createdById" DROP NOT NULL,
ALTER COLUMN "providerId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "ROOM" ADD CONSTRAINT "ROOM_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "HOSPITAL"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROOM" ADD CONSTRAINT "ROOM_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "USER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROOM_USER" ADD CONSTRAINT "ROOM_USER_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "ROOM"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROOM_USER" ADD CONSTRAINT "ROOM_USER_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MESSAGE" ADD CONSTRAINT "MESSAGE_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "USER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MESSAGE" ADD CONSTRAINT "MESSAGE_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "ROOM"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MESSAGE_VIEWED_USER" ADD CONSTRAINT "MESSAGE_VIEWED_USER_messageId_fkey" FOREIGN KEY ("messageId") REFERENCES "MESSAGE"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MESSAGE_VIEWED_USER" ADD CONSTRAINT "MESSAGE_VIEWED_USER_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PATIENT" ADD CONSTRAINT "PATIENT_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "HOSPITAL"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCHEDULING" ADD CONSTRAINT "SCHEDULING_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "HOSPITAL"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCHEDULING" ADD CONSTRAINT "SCHEDULING_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "USER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCHEDULING" ADD CONSTRAINT "SCHEDULING_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "USER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCHEDULING" ADD CONSTRAINT "SCHEDULING_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "PATIENT"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EXAM" ADD CONSTRAINT "EXAM_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "HOSPITAL"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EXAM" ADD CONSTRAINT "EXAM_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "USER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EXAM" ADD CONSTRAINT "EXAM_providerId_fkey" FOREIGN KEY ("providerId") REFERENCES "USER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EXAM" ADD CONSTRAINT "EXAM_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "PATIENT"("id") ON DELETE CASCADE ON UPDATE CASCADE;
